### ISSUE TITLE
Add more convert

### ISSUE THREAD

**Issue by shanexi** [myshell-ai/ComfyUI-ShellAgent-Plugin#6]

**Comment by shanexi** [comment]
6. ShellAgent Plugin
    1. image input convert
    2. output convert
    3. save video

**Comment by tiancheng-myshell** [comment]
周一提测

**Comment by shanexi** [comment]
todo
- image type is combo, cannot connect
- output text/integer/float default state is a widget other than a input

**Comment by shanexi** [comment]
- replace load image with shell agent input image

**Comment by shanexi** [comment]
1. duplicated items on drag output
2. delete node when replace with shell agent input image
